### ISSUE TITLE
Trouble with exception_handler

### ISSUE THREAD

**Issue by jboes** [jkitchin/jasp#56]
An interesting error occurs with the new exception handler feature. Running the following:

```javascript
from jasp import *
from ase import Atoms, Atom
import numpy as np
from ase.db import connect

atoms = Atoms([Atom('C', [0,   0, 0]),
               Atom('O', [1.2, 0, 0])])

db = connect('temp2.db')

for a in [4, 5, 6, 8, 10]:

    atoms.set_cell([a, a, a], scale_atoms=False)
    atoms.center()

    with jasp('molecules/co-L-{0}'.format(a),
              encut=350,
              xc='PBE',
              atoms=atoms) as calc:
        atoms = calc.get_atoms()
        nrg = atoms.get_potential_energy()

    db.write(atoms)
```

Will result in the the following exception:

```javascript
Traceback (most recent call last):
  File "<stdin>", line 23, in <module>
  File "/home-research/jboes/python/ase/ase/db/core.py", line 140, in new_method
    return method(self, *args, **kwargs)
  File "/home-research/jboes/python/ase/ase/db/core.py", line 201, in write
    id = self._write(atoms, kvp, data)
  File "/home-research/jboes/python/ase/ase/db/sqlite.py", line 190, in _write
    row = AtomsRow(atoms)
  File "/home-research/jboes/python/ase/ase/db/row.py", line 67, in __init__
    dct = atoms2dict(dct)
  File "/home-research/jboes/python/ase/ase/db/row.py", line 49, in atoms2dict
    dct['calculator_parameters'] = atoms.calc.todict()
  File "/home-research/jboes/python/jasp/jasp/serialize.py", line 109, in calc_to_dict
    d['data']['total_energy'] = atoms.get_potential_energy()
  File "/home-research/jboes/python/ase/ase/atoms.py", line 641, in get_potential_energy
    energy = self._calc.get_potential_energy(self)
  File "/home-research/jboes/python/ase/ase/calculators/vasp.py", line 722, in get_potential_energy
    self.update(atoms)
  File "/home-research/jboes/python/ase/ase/calculators/vasp.py", line 430, in update
    self.calculate(atoms)
  File "/home-research/jboes/python/jasp/jasp/jasp_extensions.py", line 469, in calculate
    original_calculate(self, atoms)
  File "/home-research/jboes/python/ase/ase/calculators/vasp.py", line 585, in calculate
    self.run()
  File "/home-research/jboes/python/jasp/jasp/jasp_extensions.py", line 576, in run
    raise VaspSubmitted(out)
jasp.jasp_exceptions.VaspSubmitted: 1380032.gilgamesh.cheme.cmu.edu
```
The ase database attempts to call the incomplete calculator from the atoms object. Upon failing to produce the potential energy _it submits the job a second time_.

I've been seeing other unusual behavior when using ase database in conjunction with jasp as well. If for any reason the exception handler is entered during a loop over multiple directories, the script will break any existing links to open ase databases and fail to make any future calls. This error is difficult to reproduce though.

I'm not sure there is an easy fix for these problems. The exception handler may not be worth perusing.

**Comment by jboes** [comment]
Never mind. This is not an issue specific to the exception handler.
